muzzle {
  pass {
    name = 'reactor-netty-1'
    group = "io.projectreactor.netty"
    module = 'reactor-netty-http'
    versions = "[1.0.0,)"
    assertInverse = true
  }
}

apply from: "$rootDir/gradle/java.gradle"

dependencies {
  compileOnly group: 'io.projectreactor.netty', name: 'reactor-netty-http', version: '1.0.0'
  compileOnly project(':dd-java-agent:instrumentation:netty:netty-4.1')
}
